### PR TITLE
Consume push notifications and display in textbox

### PR DESCRIPTION
**Pull request by AmberWilkie**
PT story: https://www.pivotaltracker.com/story/show/136479681

Changes:
- Subscribes to `notes_#` channel based on facility id.
- Displays cables pushed to that channel

To do:
- Get the damn text in the middle of the box. @diraulo help?

screen shot 2017-01-16 at 12 10 51 pm

### CODE REVIEW

**Comment by tochman** [comment]
@diraulo Can you please take a look at this and make sure it will work on production but also on CI

**Comment by diraulo** [comment]
@tochman @AmberWilkie I had a few questions about this one... What kind of messages are they going to display in here? How long are they going to be?

We have to keep in mind that people are not necessarily going to scroll that section of the view, and for that, I think we should have a limited number of characters to display in there.

As for failure on CI, we need to run `bower install` locally and resolve conflicts with AngularJS versions

**Comment by AmberWilkie** [comment]
@diraulo We could limit the characters. We should definitely not expect them to scroll. Suggestion for character length? Thomas was requesting that the text shrink to fit but obviously we would need to have some upper limit on the textbox to send a notification as well. @tochman ?

**Comment by diraulo** [comment]
Build is getting stuck on the `protractor` command.. I'm looking into this..

**Comment by AmberWilkie** [comment]
@diraulo I was hoping you would come in and save me from CSS hell by aligning the text inside the box centered horizontally and vertically. I left those problems and comments in the CSS because I can't freakin' figure it out.

**Comment by diraulo** [comment]
@AmberWilkie I want to work on that but we still need to decide what to do with the length of the content that'll be displayed in there. We could settle for 160 chars (you can say a lot in an SMS) or a little bit more if necessary.

**Comment by AmberWilkie** [comment]
@diraulo Ok that's fine. I'll add it to the pending PR on the server.

And, done.

**Comment by tochman** [comment]
Going green now.... @diraulo && @AmberWilkie

**Review by diraulo — APPROVED** [review]
I disabled the protractor tests.. couldn't get it working last night and I spent more time than I should've already trying to solve it. @AmberWilkie If this works fine on your local machine we can merge this in and I'll create a new later today

**Comment by AmberWilkie** [comment]
@diraulo @tochman Yeah it's been working fine locally. I haven't gotten the server side to work on heroku yet so I can't test yet if it communicates with that guy, but it talks to localhost just fine.

**Comment by AmberWilkie** [comment]
@diraulo @tochman Now that I've finally broken away from the kids and their horrible installation problems, this thing was quick to fix. I'm seeing messages come across locally on the client that were sent from heroku, so I think everything is going well. If we want to test if this works in production, we will need to configure the client differently (for when we push to the app store, for instance).

**Comment by AmberWilkie** [comment]
Also, for when it comes up, the way to clear the message is to just send a blank message. Timeouts are to be handled on another feature, but that's the MVP way of wiping messages.

**Comment by AmberWilkie** [comment]
@diraulo @tochman Ok so... the action cable works, but the polling isn't working. I don't know what's happened.... I don't get the `polling` console log either.

**Pull request merged**
